name: CI

on:
    push:
        branches: ["**"] # run on all branches for now
    pull_request:
        branches: ["**"]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.23"

            # Only needed on Linux because go-hid depends on libudev
            - name: Install Linux dependencies
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libudev-dev libusb-1.0-0-dev

            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                  path: |
                      ~/go/pkg/mod
                      ~/.cache/go-build
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Build
              run: go build ./...

            - name: Test
              run: go test ./...
