name: Release

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    # Regular tagged release
    goreleaser:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Install Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libudev-dev libusb-1.0-0-dev

            - name: Run GoReleaser (full release)
              uses: goreleaser/goreleaser-action@v6
              with:
                  distribution: goreleaser
                  version: v2.12.3
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Snapshot builds you can trigger manually
    snapshot:
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-go@v5
              with:
                  go-version: "1.22"

            - name: Install Linux dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libudev-dev libusb-1.0-0-dev

            - name: Run GoReleaser (snapshot mode)
              uses: goreleaser/goreleaser-action@v6
              with:
                  distribution: goreleaser
                  version: v2.12.3
                  args: release --snapshot --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Upload snapshot artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: mbuddy-snapshot-${{ github.sha }}
                  path: dist/**
                  if-no-files-found: error
                  retention-days: 7
